from datetime import datetime

{'[MEL]_[LC_6]_[TVFA] [CAPTAÇÃO] [LEADS]': {'last_five_minutes': {'average_cpc': 0.0,
                                                                  'campaign_budget': 'customers/1309808784/campaignBudgets/13005857988',
                                                                  'clicks': 0,
                                                                  'cost_micros': 104297,
                                                                  'ctr': 0.0,
                                                                  'date': datetime.datetime(2023, 10, 17, 17, 13, 17, 732264),
                                                                  'device': 6,
                                                                  'id': 20618685329,
                                                                  'impressions': 4,
                                                                  'optimization_score': 0.0,
                                                                  'status': 3},
                                            'last_fiveteen_minutes': {'average_cpc': 0.0,
                                                                      'campaign_budget': 'customers/1309808784/campaignBudgets/13005857988',
                                                                      'clicks': 0,
                                                                      'cost_micros': 104297,
                                                                      'ctr': 0.0,
                                                                      'date': datetime.datetime(2023, 10, 17, 17, 13, 27, 349509),
                                                                      'device': 6,
                                                                      'id': 20618685329,
                                                                      'impressions': 36,
                                                                      'optimization_score': 0.0,
                                                                      'status': 3},
                                            'memory_reference': {'average_cpc': 0.0,
                                                                 'campaign_budget': 'customers/1309808784/campaignBudgets/13005857988',
                                                                 'clicks': 0,
                                                                 'cost_micros': 104297,
                                                                 'ctr': 0.0,
                                                                 'date': datetime.datetime(2023, 10, 17, 17, 13, 12, 250257),
                                                                 'device': 6,
                                                                 'id': 20618685329,
                                                                 'impressions': 36,
                                                                 'optimization_score': 0.0,
                                                                 'status': 3}}}
